version: '3.8'

services:
    doh-server:
      image: doh-server
      build:
          context: .
          dockerfile: ./Dockerfile.alpine
      container_name: doh-server
      volumes:
          - ./server-custom/:/server-custom/
      restart: always
      network_mode: host
      healthcheck:
          test: ["CMD", "wget", "-qO/dev/null", "http://localhost:8053/dns-query?name=check.dns.sh&type=A"]
          interval: 30s
          timeout: 10s
          start_period: 30s
          retries: 3
